name: warranty_appp
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.5
  flutter_local_notifications: ^9.6.0
  timezone: ^0.8.0
  rxdart: ^0.27.4
  local_auth:
  get_it:
  pinput: ^2.2.16
  get_storage:
  intl:
  file_picker:
  share_plus:
  path_provider:
  gallery_saver:
  open_filex: ^4.3.1
  google_fonts:
  flutter_svg: ^1.1.6
  flutter_speed_dial: ^6.2.0
  connectivity_plus:
  permission_handler:
  dropdown_textfield: ^1.0.6
  rate_my_app: ^1.1.3
  vibration: ^1.7.6
  url_launcher:
  cupertino_icons: ^1.0.2
  yodo1mas: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:

  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#ffffff"
  fullscreen: true
  android: false
  ios: true

  android_12:
    android: false
    fullscreen: true
    ios: true

  web: false

flutter:

  uses-material-design: true
  assets:
    - image/